const API = "http://localhost:5000/api";
const token = localStorage.getItem("ecotech-token");
let profile, map, googleMaps, cachedBins = [];
const $ = (selector, root = document) => root.querySelector(selector);
const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char]));
const initials = name => String(name).split(" ").map(part => part[0]).slice(0, 2).join("").toUpperCase();
const imageData = file => new Promise((resolve, reject) => { if (!file) return resolve(null); if (!/^image\/(jpeg|png|webp)$/.test(file.type)) return reject(new Error("Use a JPG, PNG, or WebP image.")); if (file.size > 2 * 1024 * 1024) return reject(new Error("Image must be smaller than 2 MB.")); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(new Error("Unable to read the selected image.")); reader.readAsDataURL(file); });

async function request(path, options = {}) {
  let response;
  try { response = await fetch(API + path, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...options.headers } }); }
  catch { throw new Error("Unable to reach the server. Make sure the backend is running on port 5000."); }
  const payload = await response.json().catch(() => ({}));
  if (response.status === 401) { localStorage.removeItem("ecotech-token"); localStorage.removeItem("ecotech-user"); location.href = "../index.html"; throw new Error("Your session has expired."); }
  if (!response.ok) throw new Error(payload.message || "Unable to complete the request.");
  return payload;
}
const get = path => request(path);
const post = (path, body) => request(path, { method: "POST", body: JSON.stringify(body) });
const put = (path, body) => request(path, { method: "PUT", body: JSON.stringify(body) });
const del = path => request(path, { method: "DELETE" });
function toast(message, type = "success") { const element = document.createElement("div"); element.className = `toast text-bg-${type === "error" ? "danger" : type === "info" ? "primary" : "success"} border-0`; element.innerHTML = `<div class="d-flex"><div class="toast-body">${esc(message)}</div><button class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div>`; $("#toastArea").append(element); const instance = new bootstrap.Toast(element, { delay: 3500 }); instance.show(); element.addEventListener("hidden.bs.toast", () => element.remove()); }
function stateBadge(state) { const name = String(state || "Pending"); const cls = ({ Pending: "pending", Assigned: "assigned", "In Progress": "assigned", Completed: "completed", Cancelled: "cancelled", Open: "open", Resolved: "completed" })[name] || "pending"; return `<span class="badge ${cls}">${esc(name)}</span>`; }
function binPin(color) { return { path: googleMaps.SymbolPath.CIRCLE, scale: 9, fillColor: color, fillOpacity: 1, strokeColor: "#fff", strokeWeight: 3 }; }
function setIdentity(data) { profile = data; const name = data.full_name; $("#sideName").textContent = name; $("#topName").textContent = name; $("#sideAvatar").textContent = $("#topAvatar").textContent = initials(name); }
function intro() { return `<div class="welcome"><div><h2>Welcome, ${esc(profile.full_name.split(" ")[0])} 👋</h2><p>Help keep Ballari clean by reporting waste and collection needs.</p></div><span class="tag"><i class="fa-solid fa-location-dot me-1"></i>Ballari, Karnataka</span></div>`; }

async function dashboard() {
  const response = await get("/citizen/dashboard"); const { stats, bins } = response.data; cachedBins = bins;
  return `${intro()}<div class="stats">${[["fa-clipboard-list", "My Requests", stats.requests], ["fa-clock", "Active Requests", stats.activeRequests], ["fa-circle-check", "Completed", stats.completedRequests], ["fa-message", "Open Complaints", stats.openComplaints]].map(card => `<article class="card stat"><i class="fa-solid ${card[0]}"></i><small>${card[1]}</small><b>${card[2]}</b></article>`).join("")}</div><div class="columns"><section class="card"><div class="head"><div><h3>Nearby Garbage Bins</h3><p>Live capacity status in your area</p></div><button class="secondary" data-page="map">Open map</button></div><div id="homeMap" class="map"></div></section><section class="card"><div class="head"><div><h3>Quick Actions</h3><p>Get help in just a few taps</p></div></div><div class="quick"><button data-page="request"><i class="fa-solid fa-calendar-plus"></i>Request collection</button><button data-page="complaints"><i class="fa-solid fa-triangle-exclamation"></i>Report an issue</button><button data-page="requests"><i class="fa-solid fa-clipboard-list"></i>Track requests</button><button data-page="map"><i class="fa-solid fa-map-location-dot"></i>Find a bin</button></div><div class="head mt-4"><div><h3>Latest Updates</h3><p>Notifications for you</p></div><button class="secondary" data-page="notifications">View all</button></div><div id="homeNotices" class="empty">Loading updates...</div></section></div>`;
}
async function requestPage() { const response = await get("/citizen/bins"); cachedBins = response.data; return `<div class="page-intro"><h2>Request Garbage Collection</h2><p>Tell us where collection is needed. The city team will assign a driver.</p></div><form id="collectionForm" class="card"><div class="row g-3"><div class="col-md-6"><label class="form-label">Request type</label><select id="requestType" class="form-select" required><option value="">Select request type</option><option>Garbage Collection</option><option>Bulk Waste Collection</option><option>Overflowing Bin</option></select></div><div class="col-md-6"><label class="form-label">Nearby bin (optional)</label><select id="requestBin" class="form-select"><option value="">No specific bin</option>${cachedBins.map(bin => `<option value="${bin.id}">${esc(bin.bin_code)} — ${esc(bin.location)}</option>`).join("")}</select></div><div class="col-md-6"><label class="form-label">Location</label><input class="form-control" id="requestLocation" required maxlength="180" placeholder="e.g. Gandhi Nagar, Ballari"></div><div class="col-md-6"><label class="form-label">Preferred date (optional)</label><input class="form-control" id="requestDate" type="date"></div><div class="col-12"><label class="form-label">Details (optional)</label><textarea class="form-control" id="requestDescription" rows="4" maxlength="1000" placeholder="Add useful location or waste details..."></textarea></div></div><button class="primary big mt-3">Submit Collection Request</button></form>`; }
async function mapPage() { const response = await get("/citizen/bins"); cachedBins = response.data; return `<div class="page-intro"><h2>Garbage Bin Map</h2><p>Green: normal · Yellow: nearing capacity · Red: collection required.</p></div><section class="card"><div class="head"><div><h3>Ballari public bins</h3><p>Choose a bin when creating a collection request.</p></div><button class="secondary" id="centerMap"><i class="fa-solid fa-crosshairs"></i>Center</button></div><div id="binMap" class="map large"></div></section>`; }
async function requestsPage() { const response = await get("/citizen/requests"); const rows = response.data; return `<div class="page-intro"><h2>My Collection Requests</h2><p>Track every collection request you have submitted.</p></div><section class="card table-wrap"><table class="table"><thead><tr><th>Request</th><th>Location</th><th>Type</th><th>Date</th><th>Driver</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.length ? rows.map(item => `<tr><td>REQ-${item.id}</td><td>${esc(item.location)}</td><td>${esc(item.request_type)}</td><td>${item.created_at ? new Date(item.created_at).toLocaleDateString("en-IN") : "—"}</td><td>${esc(item.driver_name || "Awaiting assignment")}</td><td>${stateBadge(item.status)}</td><td>${item.status === "Pending" ? `<button class="action danger" data-cancel="${item.id}">Cancel</button>` : "—"}</td></tr>`).join("") : `<tr><td colspan="7"><div class="empty"><i class="fa-solid fa-clipboard"></i>No requests yet.</div></td></tr>`}</tbody></table></section>`; }
async function complaintsPage() { const response = await get("/citizen/complaints"); const rows = response.data; return `<div class="page-intro"><h2>Report a Complaint</h2><p>Report missed collection, damaged bins, or illegal dumping.</p></div><div class="columns"><form id="complaintForm" class="card"><label class="form-label">Category</label><select id="complaintCategory" class="form-select mb-3" required><option value="">Select category</option><option>Overflowing Garbage</option><option>Missed Collection</option><option>Damaged Bin</option><option>Illegal Dumping</option><option>Other</option></select><label class="form-label">Priority</label><select id="complaintPriority" class="form-select mb-3"><option>Medium</option><option>Low</option><option>High</option><option>Critical</option></select><label class="form-label">Location</label><input id="complaintLocation" class="form-control mb-3" required maxlength="180" placeholder="e.g. Cowl Bazaar"><label class="form-label">Description</label><textarea id="complaintDescription" class="form-control mb-3" required maxlength="1000" rows="4" placeholder="Describe the issue..."></textarea><label class="form-label">Photo (optional, JPG/PNG/WebP, max 2 MB)</label><input id="complaintImage" class="form-control mb-3" type="file" accept="image/jpeg,image/png,image/webp"><button class="primary big">Submit Complaint</button></form><section class="card"><div class="head"><div><h3>My Complaints</h3><p>Recent reports</p></div></div>${rows.length ? rows.map(item => `<div class="request-row"><i class="fa-regular fa-message text-danger"></i><div><b>${esc(item.category)}</b><small>${esc(item.location)} · ${new Date(item.created_at).toLocaleDateString("en-IN")}</small></div>${stateBadge(item.status)}</div>`).join("") : `<div class="empty">No complaints submitted.</div>`}</section></div>`; }
async function notificationsPage() { const response = await get("/citizen/notifications"); const rows = response.data; return `<div class="page-intro"><h2>Notifications</h2><p>Updates about your requests and the waste collection service.</p></div><section class="card">${rows.length ? rows.map(item => `<div class="notice"><i class="fa-solid ${item.type === "success" ? "fa-circle-check" : "fa-bell"}"></i><div class="flex-grow-1"><b>${esc(item.message)}</b><small>${new Date(item.created_at).toLocaleString("en-IN")}</small></div>${!item.is_read ? `<button class="action" data-read="${item.id}">Mark read</button>` : ""}<button class="action danger" data-delete-notice="${item.id}"><i class="fa-solid fa-trash"></i></button></div>`).join("") : `<div class="empty"><i class="fa-regular fa-bell"></i>No notifications yet.</div>`}</section>`; }
async function profilePage() { const response = await get("/citizen/profile"); setIdentity(response.data); return `<div class="page-intro"><h2>My Profile</h2><p>Manage your citizen account details.</p></div><form id="profileForm" class="card"><div class="d-flex align-items-center gap-3 mb-4"><span class="avatar" style="width:56px;height:56px;font-size:20px">${initials(profile.full_name)}</span><div><h5 class="mb-1">${esc(profile.full_name)}</h5><small class="text-muted">Active citizen account · Member since ${new Date(profile.created_at).toLocaleDateString("en-IN")}</small></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" id="profileName" value="${esc(profile.full_name)}" required></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" id="profilePhone" value="${esc(profile.phone)}" pattern="[0-9]{10}" required></div><div class="col-12"><label class="form-label">Email</label><input class="form-control" value="${esc(profile.email)}" disabled></div></div><button class="primary mt-3">Save Profile</button></form>`; }

function mapError(element, message) { element.innerHTML = `<div class="empty"><i class="fa-solid fa-map-location-dot"></i><b>Google Maps is unavailable</b><p>${esc(message)}</p></div>`; }
async function renderMap(elementId) { const element = document.getElementById(elementId); try { googleMaps = await loadGoogleMaps(); element.innerHTML = ""; map = new googleMaps.Map(element, { center: { lat: 15.145, lng: 76.921 }, zoom: 14, mapTypeControl: true, fullscreenControl: true, streetViewControl: false }); cachedBins.forEach(bin => { if (!bin.latitude || !bin.longitude) return; const color = bin.status === "Full" || bin.priority === "Urgent" ? "#ed5960" : bin.status === "Almost Full" || Number(bin.current_level) >= 70 ? "#e5ac2d" : "#15aa7a"; const marker = new googleMaps.Marker({ position: { lat: Number(bin.latitude), lng: Number(bin.longitude) }, map, icon: binPin(color), title: bin.bin_code }); const popup = new googleMaps.InfoWindow({ content: `<b>${esc(bin.bin_code)}</b><br>${esc(bin.location)}<br>Fill level: ${esc(bin.current_level)}%<br>Status: ${esc(bin.status)}` }); marker.addListener("click", () => popup.open({ map, anchor: marker })); }); } catch (err) { mapError(element, err.message); } }
async function loadUnread() { try { const response = await get("/citizen/notifications"); const count = response.data.filter(item => !item.is_read).length; $("#unread").textContent = count || ""; $("#navUnread").textContent = count || ""; const home = $("#homeNotices"); if (home) home.innerHTML = response.data.slice(0, 3).map(item => `<div class="notice"><i class="fa-solid fa-bell"></i><div><b>${esc(item.message)}</b><small>${new Date(item.created_at).toLocaleString("en-IN")}</small></div></div>`).join("") || "<div class='empty'>No new notifications.</div>"; } catch {} }
const titles = { dashboard: "Citizen Dashboard", request: "Request Collection", map: "Garbage Bin Map", requests: "My Requests", complaints: "Complaints", notifications: "Notifications", profile: "My Profile" };
async function render(page = "dashboard") { const pages = { dashboard, request: requestPage, map: mapPage, requests: requestsPage, complaints: complaintsPage, notifications: notificationsPage, profile: profilePage }; try { $("#pageContent").innerHTML = await pages[page](); $("#pageTitle").textContent = titles[page]; document.querySelectorAll("[data-page]").forEach(link => link.classList.toggle("active", link.dataset.page === page)); if (page === "dashboard") { setTimeout(() => renderMap("homeMap"), 20); loadUnread(); } if (page === "map") setTimeout(() => renderMap("binMap"), 20); if (innerWidth < 1000) $("#sidebar").classList.remove("show"); } catch (err) { $("#pageContent").innerHTML = `<section class="card empty"><i class="fa-solid fa-triangle-exclamation"></i><b>Unable to load this page.</b><p>${esc(err.message)}</p><button class="primary" onclick="renderCitizen('${page}')">Try again</button></section>`; } }

document.addEventListener("DOMContentLoaded", async () => {
  if (!token) { location.href = "../index.html"; return; }
  $("#today").textContent = new Intl.DateTimeFormat("en-IN", { weekday: "short", day: "numeric", month: "short", year: "numeric" }).format(new Date());
  try { const response = await get("/citizen/profile"); setIdentity(response.data); await render(); } catch (err) { toast(err.message, "error"); }
  document.addEventListener("click", event => { const nav = event.target.closest("[data-page]"); if (nav) { event.preventDefault(); render(nav.dataset.page); } if (event.target.closest("#menu")) $("#sidebar").classList.toggle("show"); if (event.target.closest("#logout")) { localStorage.removeItem("ecotech-token"); localStorage.removeItem("ecotech-user"); location.href = "../index.html"; } const cancel = event.target.closest("[data-cancel]"); if (cancel && confirm("Cancel this pending collection request?")) put(`/citizen/requests/${cancel.dataset.cancel}/cancel`, {}).then(result => { toast(result.message); render("requests"); }).catch(err => toast(err.message, "error")); const read = event.target.closest("[data-read]"); if (read) put(`/citizen/notifications/${read.dataset.read}/read`, {}).then(() => { render("notifications"); loadUnread(); }).catch(err => toast(err.message, "error")); const remove = event.target.closest("[data-delete-notice]"); if (remove) del(`/citizen/notifications/${remove.dataset.deleteNotice}`).then(() => { toast("Notification deleted."); render("notifications"); loadUnread(); }).catch(err => toast(err.message, "error")); if (event.target.closest("#centerMap") && map) { map.setCenter({ lat: 15.145, lng: 76.921 }); map.setZoom(14); } });
  document.addEventListener("submit", event => { if (event.target.id === "collectionForm") { event.preventDefault(); post("/citizen/requests", { bin_id: $("#requestBin").value || null, request_type: $("#requestType").value, location: $("#requestLocation").value, scheduled_date: $("#requestDate").value || null, description: $("#requestDescription").value }).then(result => { toast(result.message); render("requests"); }).catch(err => toast(err.message, "error")); } if (event.target.id === "complaintForm") { event.preventDefault(); imageData($("#complaintImage").files[0]).then(image => post("/citizen/complaints", { category: $("#complaintCategory").value, priority: $("#complaintPriority").value, location: $("#complaintLocation").value, description: $("#complaintDescription").value, image })).then(result => { toast(result.message); render("complaints"); }).catch(err => toast(err.message, "error")); } if (event.target.id === "profileForm") { event.preventDefault(); put("/citizen/profile", { full_name: $("#profileName").value, phone: $("#profilePhone").value }).then(result => { profile.full_name = $("#profileName").value; profile.phone = $("#profilePhone").value; setIdentity(profile); toast(result.message); }).catch(err => toast(err.message, "error")); } });
});
window.renderCitizen = render;
