const express = require("express");
const auth = require("../middleware/authMiddleware");
const requireCitizen = require("../middleware/requireCitizen");
const audit = require("../middleware/audit");
const citizen = require("../controllers/citizenController");
const ratings = require("../controllers/ratingController");
const router = express.Router();
router.use(auth, requireCitizen, audit("citizen"));
router.get("/dashboard", citizen.dashboard);
router.get("/bins", citizen.bins);
router.route("/requests").get(citizen.listRequests).post(citizen.createRequest);
router.put("/requests/:id/cancel", citizen.cancelRequest);
router.get("/ratings", ratings.listMine);
router.post("/requests/:id/rating", ratings.create);
router.route("/complaints").get(citizen.listComplaints).post(citizen.createComplaint);
router.get("/notifications", citizen.notifications);
router.put("/notifications/:id/read", citizen.readNotification);
router.delete("/notifications/:id", citizen.deleteNotification);
router.route("/profile").get(citizen.profile).put(citizen.updateProfile);
module.exports = router;
