const express = require("express");
const auth = require("../middleware/authMiddleware");
const requireDriver = require("../middleware/requireDriver");
const driver = require("../controllers/driverController");
const router = express.Router();
router.use(auth, requireDriver);
router.get("/dashboard/stats", driver.dashboardStats);
router.get("/route/today", driver.todayRoute);
router.get("/bins", driver.assignedBins);
router.get("/bins/:id", driver.binDetails);
router.put("/bins/:id/collect", driver.collectBin);
router.put("/bins/:id/skip", driver.skipBin);
router.post("/location", driver.updateLocation);
router.post("/problems", driver.reportProblem);
router.get("/collection-history", driver.collectionHistory);
router.get("/notifications", driver.notifications);
router.put("/notifications/:id/read", driver.readNotification);
router.get("/profile", driver.profile);
router.put("/profile", driver.updateProfile);
router.put("/status", driver.updateStatus);
module.exports = router;
