const express = require("express");
const auth = require("../middleware/authMiddleware");
const requireDriver = require("../middleware/requireDriver");
const audit = require("../middleware/audit");
const driver = require("../controllers/driverController");
const proof = require("../controllers/collectionProofController");
const fuel = require("../controllers/fuelController");
const router = express.Router();
router.use(auth, requireDriver, audit("driver"));
router.get("/dashboard/stats", driver.dashboardStats);
router.get("/route/today", driver.todayRoute);
router.get("/routes", driver.myRoutes);
router.get("/bins", driver.assignedBins);
router.get("/bins/:id", driver.binDetails);
router.put("/bins/:id/collect", proof.collect);
router.put("/bins/:id/skip", driver.skipBin);
router.post("/location", driver.updateLocation);
router.post("/problems", driver.reportProblem);
router.get("/collection-history", driver.collectionHistory);
router.get("/fuel-logs", fuel.listMine);
router.post("/fuel-logs", fuel.create);
router.get("/notifications", driver.notifications);
router.put("/notifications/:id/read", driver.readNotification);
router.get("/profile", driver.profile);
router.put("/profile", driver.updateProfile);
router.put("/status", driver.updateStatus);
module.exports = router;
